# Generated by Django 3.0.3 on 2021-04-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210417_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='adj',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ques',
            name='close',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ques',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ques',
            name='high',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ques',
            name='low',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ques',
            name='open1',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ques',
            name='symbol',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ques',
            name='vol',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
